@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class City {
  + City(): 
  - zipcode: int
  - Name: String
   Name: String
   zipcode: int
}
class Community {
  + Community(): 
  - zip: int
  - community: ArrayList<House>
   zip: int
   community: ArrayList<House>
}
class Doctor {
  + Doctor(): 
  - personcommunity: String
  - city: String
  - doctor: Doctor
  - vitalSignsHistory: VitalSignsHistory
  - primaryDoctorName: String
  - personhouse: String
  - age: int
  - doctorID: String
   vitalSignsHistory: VitalSignsHistory
   primaryDoctorName: String
   doctorID: String
   personcommunity: String
   age: int
   doctor: Doctor
   city: String
   personhouse: String
}
class DoctorDirectory {
  + DoctorDirectory(): 
  ~ DoctorList: ArrayList<Doctor>
   DoctorList: ArrayList<Doctor>
}
class Encounter {
  + Encounter(): 
  + Encounter(String, long, Date): 
  - timestamp: long
  - date: Date
  - patientname: String
  - history: ArrayList<VitalsSign>
  + addNewvitals(): VitalsSign
   timestamp: long
   patientname: String
   date: Date
   history: ArrayList<VitalsSign>
}
class EncounterHistory {
  + EncounterHistory(): 
  + addNewencounter(String, long, Date): void
   encounter: ArrayList<Encounter>
}
class HospitalDirectory {
  + HospitalDirectory(): 
  - hospitalNmae: String
  - hospitalZipcode: int
  - hospitaladdress: String
   hospitalZipcode: int
   hospitalNmae: String
   hospitaladdress: String
}
class House {
  + House(): 
  - city: String
  - Zip: String
   Zip: String
   city: String
   community: String
}
class MyNumericVerifier {
  + MyNumericVerifier(): 
  + verify(JComponent): boolean
}
class MyStringVerifier {
  + MyStringVerifier(): 
  + verify(JComponent): boolean
}
class Patient {
  + Patient(): 
  - primaryDoctorName: String
  - personcommunity: String
  - personhouse: String
  - vitalSignsHistory: VitalSignsHistory
  - patientID: String
  - city: String
  - patient: Patient
  - age: int
  + toString(): String
  + setcity(String): void
  + getcity(): String
   vitalSignsHistory: VitalSignsHistory
   primaryDoctorName: String
   patient: Patient
   personcommunity: String
   age: int
   city: String
   personhouse: String
   patientID: String
}
class Person {
  + Person(): 
  - personcommunity: String
  - personhouse: String
  - age: int
  - personcity: String
  - personName: String
  - doctor: Doctor
  - patient: Patient
  + toString(): String
   personcity: String
   personName: String
   personcommunity: String
   patient: Patient
   age: int
   doctor: Doctor
   personhouse: String
}
class PersonDirectory {
  + PersonDirectory(): 
  + deletePerson(Person): void
  + searchDoctor(String): ArrayList<Person>
  + searchPatient(String): ArrayList<Person>
  + searchPerson(String): ArrayList<Person>
  + createAndAddPerson(): Person
   personHistory: ArrayList<Person>
}
class Roles {
  + Roles(): 
  + roleType: String
   roleType: String
}
class UserAccount {
  + UserAccount(String, String, String): 
  + UserAccount(): 
  - role: String
  - username: String
  - password: String
  + hashCode(): int
  + equals(Object): boolean
   password: String
   username: String
   role: String
}
class UserAccountDirectory {
  + UserAccountDirectory(): 
  - userAccountList: ArrayList<UserAccount>
  + deleteUserAccount(UserAccount): void
  + getUserAccount(UserAccount): UserAccount
  + authenticateUser(String, String): UserAccount
  + createUserAccount(String, String, String): UserAccount
   userAccountList: ArrayList<UserAccount>
}
class VitalSignsHistory {
  + VitalSignsHistory(): 
  - history: ArrayList<VitalsSign>
  + createAndAddVitalSign(): VitalsSign
  + deleteVitalSign(VitalsSign): void
   history: ArrayList<VitalsSign>
}
class VitalsSign {
  + VitalsSign(): 
  - respiratoryRate: int
  - weight: int
  - timestamp: Date
  - heartRate: int
  - bloodPressure: int
  + toString(): String
   heartRate: int
   weight: int
   bloodPressure: int
   respiratoryRate: int
   timestamp: Date
}

Doctor               "1" *-[#595959,plain]-> "vitalSignsHistory\n1" VitalSignsHistory    
Encounter             -[#595959,dashed]->  VitalsSign           : "«create»"
EncounterHistory      -[#595959,dashed]->  Encounter            : "«create»"
Patient               -[#595959,dashed]->  VitalSignsHistory    : "«create»"
Patient              "1" *-[#595959,plain]-> "vitalSignsHistory\n1" VitalSignsHistory    
Person               "1" *-[#595959,plain]-> "doctor\n1" Doctor               
Person               "1" *-[#595959,plain]-> "patient\n1" Patient              
PersonDirectory       -[#595959,dashed]->  Person               : "«create»"
UserAccountDirectory  -[#595959,dashed]->  UserAccount          : "«create»"
VitalSignsHistory     -[#595959,dashed]->  VitalsSign           : "«create»"
@enduml
