/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package userInteface.Person;

import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.MyNumericVerifier;
import model.MyStringVerifier;
import model.Person;
import model.PersonDirectory;


public class CreatePersonJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form CreatePatientJPanel
     */
    private PersonDirectory personDirectory;
    private JPanel userProcessContainer;
    
    public CreatePersonJPanel(JPanel userProcessContainer,PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        addVerifiers();
    }
    
    private void addVerifiers() {
        InputVerifier integerVerifier = new MyNumericVerifier();
        personAgeJTextField.setInputVerifier(integerVerifier);
        InputVerifier stringVerifier = new MyStringVerifier();
        pesonNameJTextField.setInputVerifier(stringVerifier);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personAgeJTextField = new javax.swing.JTextField();
        addPersonJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        patientNameJLabel = new javax.swing.JLabel();
        AgeJLabel = new javax.swing.JLabel();
        pesonNameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        housejLabel = new javax.swing.JLabel();
        communityjLabel = new javax.swing.JLabel();
        cityjLabel = new javax.swing.JLabel();
        personhouse = new javax.swing.JTextField();
        personcommunity = new javax.swing.JTextField();
        personcity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(personAgeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 150, -1));

        addPersonJButton.setBackground(new java.awt.Color(0, 102, 102));
        addPersonJButton.setForeground(new java.awt.Color(255, 255, 255));
        addPersonJButton.setText("Add Person");
        addPersonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonJButtonActionPerformed(evt);
            }
        });
        add(addPersonJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 100, 36));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Person Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 446, -1));

        patientNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        patientNameJLabel.setText("Person Name");
        add(patientNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        AgeJLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AgeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        AgeJLabel.setText("Age");
        add(AgeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 108, -1));
        add(pesonNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 150, -1));

        backJButton.setBackground(new java.awt.Color(0, 102, 102));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 100, 36));

        housejLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        housejLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        housejLabel.setText("House");
        add(housejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 108, -1));

        communityjLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        communityjLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        communityjLabel.setText("Community");
        add(communityjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 108, -1));

        cityjLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cityjLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cityjLabel.setText("City");
        add(cityjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 108, -1));
        add(personhouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 150, -1));
        add(personcommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 150, -1));
        add(personcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInteface/Person/personss.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonJButtonActionPerformed
        // TODO add your handling code here:
        if (checkBlankInput()==Boolean.TRUE)
        {
            Person person=personDirectory.createAndAddPerson();
            person.setPersonName(pesonNameJTextField.getText());
            person.setAge(Integer.parseInt(personAgeJTextField.getText()));
            person.setPersonhouse(personhouse.getText());
            person.setPersoncommunity(personcommunity.getText());
            person.setPersoncity(personcity.getText());
            JOptionPane.showMessageDialog(this, "Person added!!", "Update",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter all values",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addPersonJButtonActionPerformed
    private void clearFields()
    {
        pesonNameJTextField.setText("");
        personAgeJTextField.setText("");
        personcity.setText("");
        personcommunity.setText("");
        personhouse.setText("");
    }
    private Boolean checkBlankInput()
    {
        if(pesonNameJTextField.getText().length()==0
                ||personAgeJTextField.getText().length()==0||personcity.getText().length()==0
                ||personcommunity.getText().length()==0||personhouse.getText().length()==0
                )
        {
            return false;
        }
        else{
            return true;
        }
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeJLabel;
    private javax.swing.JButton addPersonJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel cityjLabel;
    private javax.swing.JLabel communityjLabel;
    private javax.swing.JLabel housejLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel patientNameJLabel;
    private javax.swing.JTextField personAgeJTextField;
    private javax.swing.JTextField personcity;
    private javax.swing.JTextField personcommunity;
    private javax.swing.JTextField personhouse;
    private javax.swing.JTextField pesonNameJTextField;
    // End of variables declaration//GEN-END:variables
}
