/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInteface.Person;


import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.MyNumericVerifier;
import model.MyStringVerifier;
import model.Person;


public class ViewUpdatePersonDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientDetailsJPanel
     */
    private Person person;
    private JPanel userProcessContainer;
    private Boolean isEdit = Boolean.FALSE;

    public ViewUpdatePersonDetailsJPanel(JPanel userProcessContainer, Person person, Boolean isEdit) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        this.isEdit = isEdit;
        addVerifiers();
        populatePatientDetails();
        modifyTextFields(this.isEdit);
    }

    private void addVerifiers() {
        InputVerifier integerVerifier = new MyNumericVerifier();
        personAgeJTextField.setInputVerifier(integerVerifier);
        InputVerifier stringVerifier = new MyStringVerifier();
        personNameJTextField.setInputVerifier(stringVerifier);
        personhouse.setInputVerifier(stringVerifier);
        personcity.setInputVerifier(stringVerifier);
        personcommunity.setInputVerifier(stringVerifier);
    }

    private void populatePatientDetails() {
        personNameJTextField.setText(person.getPersonName());
        personAgeJTextField.setText(String.valueOf(person.getAge()));
        personhouse.setText(person.getPersonhouse());
        personcity.setText(person.getPersoncity());
        personcommunity.setText(person.getPersoncommunity());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgeJLabel = new javax.swing.JLabel();
        personNameJTextField = new javax.swing.JTextField();
        personAgeJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        patientNameJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        editJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        housejLabel = new javax.swing.JLabel();
        personhouse = new javax.swing.JTextField();
        communityjLabel = new javax.swing.JLabel();
        personcommunity = new javax.swing.JTextField();
        personcity = new javax.swing.JTextField();
        cityjLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgeJLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AgeJLabel.setText("Age");
        add(AgeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 122, -1));
        add(personNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 150, -1));
        add(personAgeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 375, -1));

        patientNameJLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        patientNameJLabel.setText("Patient Name");
        add(patientNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 122, -1));

        backJButton.setBackground(new java.awt.Color(0, 102, 102));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 100, 33));

        editJButton.setBackground(new java.awt.Color(0, 102, 102));
        editJButton.setForeground(new java.awt.Color(255, 255, 255));
        editJButton.setText("Edit");
        editJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJButtonActionPerformed(evt);
            }
        });
        add(editJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 100, 33));

        saveJButton.setBackground(new java.awt.Color(0, 102, 102));
        saveJButton.setForeground(new java.awt.Color(255, 255, 255));
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 100, 36));

        housejLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        housejLabel.setText("House");
        add(housejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 122, -1));
        add(personhouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 150, -1));

        communityjLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        communityjLabel.setText("Community");
        add(communityjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 122, -1));
        add(personcommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, -1));
        add(personcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 150, -1));

        cityjLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cityjLabel.setText("City");
        add(cityjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 122, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInteface/Person/peoplesss.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -250, 850, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void editJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJButtonActionPerformed
        // TODO add your handling code here:
        modifyTextFields(true);
    }//GEN-LAST:event_editJButtonActionPerformed

    private void modifyTextFields(Boolean isEdit) {
        if (isEdit) {
            personNameJTextField.setEnabled(true);
            personAgeJTextField.setEnabled(true);
            personhouse.setEnabled(true);
            personcommunity.setEnabled(true);
            personcity.setEnabled(true);
        } else {
            personNameJTextField.setEnabled(false);
            personAgeJTextField.setEnabled(false);
            personhouse.setEnabled(false);
            personcommunity.setEnabled(false);
            personcity.setEnabled(false);
        }
    }

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:

        if (checkBlankInput()) {
            person.setAge(Integer.parseInt(personAgeJTextField.getText()));
            person.setPersonName(personNameJTextField.getText());
            person.setPersonhouse(personhouse.getText());
            person.setPersoncommunity(personcommunity.getText());
            person.setPersoncity(personcity.getText());
            JOptionPane.showMessageDialog(this, "Person details updated!!",
                    "Update", JOptionPane.INFORMATION_MESSAGE);
            modifyTextFields(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct values", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_saveJButtonActionPerformed
    private Boolean checkBlankInput() {
        if (personAgeJTextField.getText().length() == 0
                || personNameJTextField.getText().length() == 0 || personhouse.getText().length() == 0 || personcommunity.getText().length() == 0 || personcity.getText().length() == 0) {
            return false;
        } else {
            return true;
        }
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel cityjLabel;
    private javax.swing.JLabel communityjLabel;
    private javax.swing.JButton editJButton;
    private javax.swing.JLabel housejLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel patientNameJLabel;
    private javax.swing.JTextField personAgeJTextField;
    private javax.swing.JTextField personNameJTextField;
    private javax.swing.JTextField personcity;
    private javax.swing.JTextField personcommunity;
    private javax.swing.JTextField personhouse;
    private javax.swing.JButton saveJButton;
    // End of variables declaration//GEN-END:variables
}
